package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 17 10:53:58 CEST 2018
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void refreshEmployees();
}

